### ISSUE TITLE
Add support for Compatipede 1-style "plugins"

### ISSUE THREAD

**Issue by hallvors** [Asynchq/boar#1]
It's easy to define and extend a standard set of test methods by supporting "plugins". Compatipede 1 defined three types of plugins (see [repo](https://github.com/seiflotfy/compatipede/tree/master/plugins)): 

* Plugins running on page start
* Plugins running on page load
* Plugins scanning page resources (JS and CSS files)

The easiest to implement are probably page load plugins: when the page is done loading, just evaluate all scripts and record the return values.

Plugins scanning resources should also be easyish to implement, using SlimerJS/PhantomJS onResourceReceived events.

"Page load start" type plugins return results by calling console.log() They can probably (?) be injected from a Slimer/Phantom onInitialized event, but the app need to monitor console output to get results. (Alternatively, we need to find some other feedback channel from scripts running in the page to the tab.js controller).

Work:

- [x] Add code that loads and prepares plugin data (preferably like Compatipede 1 - just scanning through .json files in a "plugins" folder)
- [x] Add a global object to store plugin results, and a URL command "getPluginResults" that will return a JSON stringification of said object. Make sure the object is reset on opening a new page
- [x] Add support for page load - type plugins
- [x] Add support for "resource scan" - type plugins
- [x] Add support for "page start" - type plugins including code to extract results from console messages (or other approach if we can find one)

**Comment by seiflotfy** [comment]
+1 love it....

**Comment by hallvors** [comment]
Turns out this is harder than expected with Phantomjs because the onResourceLoaded callback doesn't give you the actual content of the loaded resource.. :-/

**Comment by seiflotfy** [comment]
I think it's hackable



—

**Comment by hallvors** [comment]
It's on the way! See:
https://github.com/ariya/phantomjs/commit/434d4e0101a540525e8f89a657ea553fb38b040b
Maybe in Phantom 2.0.1 ?

**Comment by hallvors** [comment]
@seiflotfy how is this progressing - any code to push to Github yet? :)

**Comment by seiflotfy** [comment]
got sidetracked for a bit. I will have something done before monday promise

**Comment by hallvors** [comment]
Seems the plugin handling is feature-complete now - good work! :)
