### ISSUE TITLE
first execution from README

### ISSUE THREAD

**Issue by vecna** [Asynchq/boar#10]
Following the README as is written, on Ubuntu 15.04 (x86_64)
    
      git clone git@github.com:Asynchq/boar.git
      npm install
      bin/boar gecko

but executing boar:

     zz@zz:~/Dev/boar$ bin/boar gecko

     /home/zz/Dev/boar/bin/boar:17
       .check((argv) => {
                 ^
     SyntaxError: Unexpected token >
        at Module._compile (module.js:439:25)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:935:3

I'm using nodejs 0.10.40, apparently my IDE report an error on 'let' keyword. I'm missing something or some requirement is get lost ?

**Comment by dainis** [comment]
Right now it requires node 0.12+

bin/boar is using es6 ```let``` and fat arrow functions

looks like 0.10 even with --harmony flag doesn't have these capabilities

**Comment by vecna** [comment]
I've downloaded from the official website, probably has to be reported in the docs in some way
