### ISSUE TITLE
Why does taking a screenshot resize the viewport?

### ISSUE THREAD

**Issue by hallvors** [Asynchq/boar#12]
There's some extra resizing going on here in the screenshot method:
https://github.com/Asynchq/boar/blob/master/boar/tab.js#L265

Why?

**Comment by seiflotfy** [comment]
2 reasons:

1) websites like eBay, tend to do lazy loading (so scrolling down will start loading more stuff). If we don’t resize the bottom portion will be empty.

2) Slimerjs takes only a screenshot of what is in the window view unlike phantomjs which takes a screenshot of the page. So resizing it allows me to try to have them both have all content


—

**Comment by hallvors** [comment]
Hm.. If we want a screenshot with the lazy loading content included, perhaps something like 

    window.scrollTo(0, document.documentElement.scrollHeight)

or similar might work and be clearer? I'm not even sure that we want to force loading of lazy loaded content - perhaps the fact that some content is lazily loaded is an interesting thing to document in screenshots..? I think we can leave it up to the script that requests screenshots, or maybe give the method an option..

**Comment by hallvors** [comment]
http://docs.slimerjs.org/current/api/webpage.html#render-filename-options actually says SlimerJS defaults to full-page screenshots, so now I'm a little confused..

**Comment by seiflotfy** [comment]
Hmmmm, yeah you are right, but it does not load the whole page. So some resources are missing. I can fix that. No worries

**Comment by hallvors** [comment]
So if it's OK with you @seiflotfy I suggest we just rip out that resize code. That way, we could for example write test cases that test progressive loading by taking one screenshot just after load and another when scrolled half-way down the page, comparing them to check that progressive loading works.. At the moment it's doing too much magic ;)
