### ISSUE TITLE
Sometimes /destroy returns weird response body

### ISSUE THREAD

**Issue by dainis** [Asynchq/boar#13]
sometimes ```/destroy``` response comes back really weird, happens with phantomjs client

```
 {"success":true}HTTP/1.1 404 Not Found
Content-Type: text/plain
Content-Length: 35
Connection: close

Error 404: Not Found
```

this doesn' t happen all the time, only in some random cases

**Comment by hallvors** [comment]
Heh. Funny!

**Comment by dainis** [comment]
Took a look at phantomjs source and mongoose(web server phantomjs is using), looks like it is a race condition, when phantomjs web server is closed semaphore blocking connection thread is released and as flag about server being closed is set, falsey value is returned to mongoose which triggers it to return 404 because it falls through to another handler

small delay between sending response and closing server should do the trick
