### ISSUE TITLE
If page can't be loaded boar won't return any response and kill itself because of inactivity

### ISSUE THREAD

**Issue by dainis** [Asynchq/boar#14]
For example : https://realq.sjunet.org/IBD/login/

It doesn't load at all and tab will kill itself because of inactivity

**Comment by seiflotfy** [comment]
That is right. Because anyhow the page needs to self-destruct since we don't want people to reuse a page. But rather request a new one. So either they call a destroy themselves once done with their tests o we do it for them.

**Comment by ronoc** [comment]
What happens in the scenario whereby a genuine HTTP 408 is thrown ?

**Comment by seiflotfy** [comment]
I can't return a status code since phantom and slimer don't return status code of a page load. http://phantomjs.org/api/webpage/method/open.html all they return is success or fail. I a changing it to return fail
