### ISSUE TITLE
Plugin manager is per-tab, should be per-pageload?

### ISSUE THREAD

**Issue by hallvors** [Asynchq/boar#25]
From looking at the code, the plugin manager is set up in ```Tab.prototype.init()```.
This means that if you open, say, three pages in a row, each time you call getPluginResults you will get the accumulated results for all pages, no? I think we either need to create a new pluginManager on each open() or give the plugin manager a reset() method which we use internally on open() to forget all old results.

**Comment by seiflotfy** [comment]
No that won't happen. Because each tab runs in its own process anyhow. It does not share resources with others.

**Comment by hallvors** [comment]
I'm thinking of a case where the client script does something like this:

1. new
2. open site A
3. getPluginResults
4. open site B
5. getPluginResults

Now, if for example site A used window.orientation and site B did not, I *think* that given the current architecture we'll get a false positive flag for window.orientation usage on site B in step 5, because the plugin manager will have seen the usage on site A and remembered that.

If we want to rely on the distinction between tabs in different processes, the API would have to enforce this somehow IMO, like disallow another open call for an existing tab where one site was opened already. This would be a bad limitation that would prevent many useful cases (and could in fact just be worked around with JS injected for navigation anyway). So I'm sticking to the suggestion that we give the plugin manager a reset method, and call this from open (although if I'm actually misunderstanding something here I appreciate corrections).

**Comment by hallvors** [comment]
I see there is a reset() method. This seems handled already :)
