### ISSUE TITLE
Running multiple slimerjs jobs in parallel

### ISSUE THREAD

**Issue by dainis** [Asynchq/boar#32]
When multiple slimerjs jobs are run in parallel sometimes they silently fail when opening a page or creating a screenshot. Running only single tab works fine

And also sometimes address in use error gets thrown (there are checks in [asynchq/jannah](https://github.com/asynchq/jannah) for that so I am not sure if that is issue with slimerjs or jannah)

**Comment by ronoc** [comment]
To be thrashed as we start load testing early new year

**Comment by ronoc** [comment]
Not all that relevant for phase one, closing
