### ISSUE TITLE
Run on Windows

### ISSUE THREAD

**Issue by hallvors** [Asynchq/boar#39]
As far as I can tell, there's no way to run the bin/boar script on Windows at the moment.

```node --harmony bin\boar gecko```

gets us close, but not quite: we apparently run into https://github.com/nodejs/node-v0.x-archive/issues/5841 AKA https://github.com/nodejs/node-v0.x-archive/issues/2318 when trying to use spawn() for a node module which isn't an .exe file. I'm not sure how to get around this NOENT error.

**Comment by ronoc** [comment]
But who uses Windows :) !

**Comment by hallvors** [comment]
I use Windows quite a bit ;) but I agree with closing this - it's a problem for lots of projects and should probably be handled on the Node side. Note how many issues link to https://github.com/nodejs/node-v0.x-archive/issues/2318 .. :(
