### ISSUE TITLE
Consider responding to pings before starting something heavy

### ISSUE THREAD

**Issue by hallvors** [Asynchq/boar#59]
Sometimes plugins (or BOAR itself) need a bit of time to process an event, and as far as I can tell there are race conditions inherent in the implementation of the 5 second timeout. For example, even if some plugin uses "only" 250ms it might start doing its work when 4.9 seconds have elapsed since the previous ping, possibly or likely causing the timeout code to kill the tab and register a failed test.

Here's a suggestion: tab.js can keep track of how much time is left since the previous ping response, and do a preliminary "pong" before certain actions known to be potentially time consuming. So, before 

* onResourceReceived processing
* onInitialized processing
* onLoadFinished processing
* creating screenshot

it can call a method that just checks if there is less than 1 second left of the ping delay, and "pong" immediately if it is. This way the backend's pending timeout gets reset and the risk of race condition timeouts should be considerably reduced.

**Comment by hallvors** [comment]
@seiflotfy @ronoc  any views? I know this will solve itself when we do the WebExtensions work, but most likely we'll use Slimer/Phantom for at least 1/2 - 1 year yet (my guesstimate). It would not be that hard to add this little hack if you think it's worth it, right?

**Comment by hallvors** [comment]
(I've tried testing an implementation of this on my laptop, but since it's a few yrs old it needs a higher timeout anyway - I usually set it to 2-3 minutes..)

**Comment by ronoc** [comment]
@hallvors, not a fan to be honest, I suspect it would introduce more bugs than its worth,  I would rather focus on integrating the API and use our efforts to bed that technology in rather than spend any more time on a slimer/phantom solution. 

>>... least 1/2 - 1 year yet (my guesstimate).
The firefox release with the first iteration of web extensions is due in March.

**Comment by ronoc** [comment]
But if you want to have a go at implementing we will certainly merge it, either way the BOAR side needs a complete rewrite in the very near future.

**Comment by hallvors** [comment]
Local testing is inconclusive, I can't really tell if this improved things. I'll leave it as-is for now ;)
